### ISSUE TITLE
dvhcalc interpolation_resolution issue

### ISSUE THREAD

**Issue by peterg1t** [dicompyler/dicompyler-core#117]
Hi,

First of all, congrats on this great tool!

I'm trying to use dicmpyler-core to calculate the DVH of some files. I got a result but I wanted to try increasing the resolution as shown in the documentation.
`interpscar = dvhcalc.get_dvh("rtss.dcm", "rtdose.dcm", 8,interpolation_resolution= 2.5/16),interpolation_segments_between_planes=2,use_structure_extents=True)`
However in my file the original resolution is 2.02265 and no matter what value I use it gives me an error.

> AttributeError: New pixel spacing must be a factor of 2.02265/(2^n), where n is an integer.

Even when I use 2.02265!

> AttributeError: New pixel spacing must be a factor of 2.02265/(2^n), where n is an integer. Value provided was 2.02265.

Am I doing something wrong? Any help is appreciated. Please let me know if you need some further information or data to reproduce the problem.

Best regards

Pedro

**Comment by bastula** [comment]
Hi Pedro,

Thanks for the kind words.

As the documentation says, it should be a factor of `pixelspacing/(2^n)`. `2.5 / 16 = 0.15625` doesn't fit that criteria. However, if the original pixel spacing value is not working, there might be some other issue.

What version of Python are you using? There is a difference in Python 2.x vs 3.x. The unit tests for dicompyler-core should catch that though.

**Comment by peterg1t** [comment]
Hi Aditya,
Sorry for the late reply. Been busy with some things over here. I am using python 3.6.8. Here is a screencapture of my specs (I'm using conda in my linux box but I have the same version on windows)
![image](https://user-images.githubusercontent.com/8771255/62153935-ec567780-b2c2-11e9-8832-574962286616.png)
I was thinking of taking a closer look and run more tests but haven't had much time.

Cheer,s
Pedro

**Comment by bastula** [comment]
Hi Pedro,

I think maybe we should look at your data? You can upload an anonymized
dataset here: https://www.dropbox.com/request/CswRtx83xpOUWU3BwIQU

Aditya

**Comment by peterg1t** [comment]
Hi Aditya,
I kinda figure out what is going on. turns out that my dose file pixel spacing in the axial, sagittal and coronal directions directions is different. I try to "trick" dvhcalc by passing the value of the correct pixel spacing (in this case the dy) but I got another error. The new error says that the number of points in the mask size is different. 

> numpy.ma.cora.MaskError: Mask and data not compatible: data size is 1368, mask size is 1440.

This is a problem in the sense that my structure slices are oriented along the z-axis (parallel) therefore the dose matrix should be "sliced" in the same way. Does this makes sense? Now it is using coronal slices when it should be using axial I believe but I could be wrong.

I will try and anonymize a DICOM file and send it your way. Haven't done it before.

Cheers
Pedro

**Comment by peterg1t** [comment]
Hi Aditya,

Sorry for the late reply. I was busy with some other work around here. I sent you a structure and dose info so you can reproduce the issue and play with it. The data is from a phantom we use here for calibration but we get the same issue. 
Thanks for your help and patience. Let me know what you find, I'm very curious. Have a great day.

Pedro

**Comment by bastula** [comment]
Hi Pedro,

Thanks for sending the dataset. I am busy for the next few days but I will try to take a look at soon. I hope we can resolve the issue!

Aditya

**Comment by bastula** [comment]
I think your earlier comment was on the right track. The `dvhcalc` interpolation is currently assuming square voxels. Your dataset has different pixel spacing in the x and y (lateral, coronal) directions. I will need to make a modification to the interpolation settings in order to account for this.

**Comment by bastula** [comment]
Hi Pedro,

This issue has been resolved. Please change the new pixel resolution to a `(row, column)` tuple. For your dataset, if you wanted to interpolate to `8` times smaller in both lateral and coronal, you can use the following argument to `get_dvh` : `interpolation_resolution=(0.99728027777777 / 8, 0.98006875 / 8)`.

The existing single float value will only work for square pixel spacing.

Thank you for sending the sample dataset.

**Comment by peterg1t** [comment]
Hi Aditya,
I will use it right away and get back at you. Thank you for looking into this. I'm glad I could help with the dataset to make this awesome tool more general.
Best regards.
Pedro
