### ISSUE TITLE
Incorrect DVHs for FFS, HFP patient orientations (non-HFS?)

### ISSUE THREAD

**Issue by cutright** [dicompyler/dicompyler-core#144]
Some users of my software (which uses dicompyler-core) have noticed an issue with incorrect DVHs.  This appears to be verified when opening FFS and HFP patients in the dicompyler GUI; the structures do not properly overlay with the CT data set.

Original issue posted here: https://github.com/cutright/DVH-Analytics/issues/62

> Multiple users have identified a bug where DVHs are incorrectly calculated for Foot-First-Supine patient orientations. This appears to be an issue with dicompyler-core and can be observed by independently loading CT and RT-Structure data in the dicompyler GUI/program, the structures to do not line up with the CT.
> 
> Thanks to Mahesh and Mike for catching this.
> 
> Are there any other users out that that have observed similar behavior for other patient orientations? It would be easy to check, simply include a Patient Orientation filter in your query. The DVHs will almost certainly not monotonically decrease.
> 
> The resolution is unclear for the moment, but at a minimum I'll flag FFS plans in DVHA on import in v0.7.5 when it's released.

**Comment by bastula** [comment]
Seems this was already documented in #29. I'll leave this open until that issue is resolved.
