### ISSUE TITLE
Plot Dose distribution on CT scan

### ISSUE THREAD

**Issue by MLRadfys** [dicompyler/dicompyler-core#160]
Hi,

Iam wondering if there is an option to plot dose distributions on CT scans?

Thanks in advance,

cheers,

Michael

**Comment by bastula** [comment]
There is not inside dicompyler-core, but dicompyler itself can do this.

**Comment by MichaelLempart** [comment]
Hi and thanks for the quick reply!

I tried to write some code on my own for a project, but it seems like I have an offset between my dose distribution and my CT image. The CT images are first resampled to the dose matrices voxel size and then cropped to the same pixel size (width, height).

Nevertheless, the dose does not exactly overlay at the right position. 

Do you have any experience on that? Do I have to match the ImagePatientPosition in some way or is there any offset information in the DICOM header?

Thanks again,

kind regards,

Michael

**Comment by bastula** [comment]
Very sorry for the late reply (after coming with a quick one!)

Did you get this issue resolved?

**Comment by muslehm** [comment]
Is there an open-source code as implementation for that?
