### ISSUE TITLE
Problem import of dose module

### ISSUE THREAD

**Issue by elifoo** [dicompyler/dicompyler-core#205]
Hi,
I have 'ImportError' when I try to import dose module in my code. I use python 3.7.2. While dicomparser, dvh and dvhcalc module work fine. Any idea?
Thanks a lot

**Comment by bastula** [comment]
The `dose` module is available only in version `0.5.6` on GitHub. The PyPI package of that version is not ready, so you can obtain it via source using the following command:

`pip install git+https://github.com/dicompyler/dicompyler-core.git`

**Comment by elifoo** [comment]
Great! Now It works. Thank you!
