### ISSUE TITLE
PixelData = None causes crash

### ISSUE THREAD

**Issue by cutright** [dicompyler/dicompyler-core#213]
I came across an issue with DICOM files originating from QARC (which I believe uses CERR).  For some reason the RTPlan files contained a `PixelData` attribute.  Because it was set to `None` (rather than deleting it), the following line crashes:

https://github.com/dicompyler/dicompyler-core/blob/61d7e6672c15f7096e555535bd1daa8d2fed6a3d/dicompylercore/dicomparser.py#L66

with the error:

`TypeError: object of type 'NoneType' has no len()`

I'll submit a PR shortly.

**Comment by bastula** [comment]
Closed by #214.
