### ISSUE TITLE
'FileDataset' object has no attribute 'DVHSequence'

### ISSUE THREAD

**Issue by sama2689** [dicompyler/dicompyler-core#219]
I am trying to do the example in the docs to confirm that the package is working, I have an rt dose file and an rt struct file and my code is as follows
```

from dicompylercore import dicomparser, dvh, dvhcalc
from dicompylercore import dicomparser, dvh, dvhcalc
dp = dicomparser.DicomParser("RT-STRUCT.dcm")


# i.e. Get a dict of structure information
structures = dp.GetStructures()


rtdose=dicomparser.DicomParser("RT-DOSE.dcm")
#Stomach dvh
stomachdvh=dvh.DVH.from_dicom_dvh(rtdose.ds, 10)

```
But on the last line I get the following error
```
Traceback (most recent call last):

  File "<ipython-input-5-34a766ef1447>", line 17, in <module>
    stomachdvh=dvh.DVH.from_dicom_dvh(rtdose.ds, 10)

  File "D:\Users\me\anaconda3\envs\Python38\lib\site-packages\dicompylercore\dvh.py", line 67, in from_dicom_dvh
    for i, d in enumerate(dataset.DVHSequence):

  File "D:\Users\me\anaconda3\envs\Python38\lib\site-packages\pydicom\dataset.py", line 835, in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'FileDataset' object has no attribute 'DVHSequence

```

I installed the package from the git on python 3.8 using the command pip install git+git://github.com/dicompyler/dicompyler-core.git

Has anyone else had this problem or have a fix?

**Comment by bastula** [comment]
Hello there, it is quite possible that your RTDose file does not contain any DVH data. Only a few treatment planning systems export DVH data as part of RTDose. If this is the case, you can always manually calculate the DVH via the `dvhcalc` module and following the docs.

**Comment by sama2689** [comment]
Thanks, that worked! the following code returns a dvh objects and all relevant metrics can be retrieved as attributes.
