### ISSUE TITLE
How would I extract the 0.1cc value from a DVH?

### ISSUE THREAD

**Issue by sama2689** [dicompyler/dicompyler-core#222]
Apologies if this has been answered somewhere but I was unable to easily find the syntax in the docs. Just based on example it seems that it's easy enough to get the 2cc value of a dvh by just typing in dvh.D2cc, however how would I do this for values that are not integers? e.g. 0.1cc?

typing in dvh.D0.1cc of course doesn't work as the . will confuse python.

I have also tried 

`dvh.statistic(dvh,'D0.1cc')`
which returns a type error as well as 

`dvh.dose_constraint(dvh,0.1,volume_units=cc)`
which returns 'cc' is not defined.

**Comment by sama2689** [comment]
I answered my own question, 
`dvh.statistic('D0.1cc')`
should work.

**Comment by bastula** [comment]
Great! That's correct!
