### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by bobred** [dicompyler/dicompyler-core#226]
Hi
Is there a way to disable logging?
Thanks

**Comment by bastula** [comment]
Is there a specific module you want to disable logging in? Otherwise you can disable logging for the logger called `dicompyler`.

**Comment by bobred** [comment]
I am using dvhcalc but if it can be disabled globally that would be great.

**Comment by bobred** [comment]
Hi
Figured it out, i used 

    import logging
    log = logging.getLogger('dicompylercore.dvhcalc')
    log.disabled = True

Thanks
