### ISSUE TITLE
Calcdvh function performance when contour and rtdose planes are not the same.

### ISSUE THREAD

**Issue by sama2689** [dicompyler/dicompyler-core#235]
I have a modified contour as a 'set of points' dict and I want to computer the dvh of this contour from a particular rtdose file. However, the slices of the contour are not co-planar. I.e. the slice location of rtdose may not necessarily match the slice location of the structure. Would the[ `_calculate_dvh` ](https://dicompyler-core.readthedocs.io/en/latest/_modules/dicompylercore/dvhcalc.html#get_dvh)function still evaluate correctly in this case or would I have to interpolate the contour to match the rtdose planes?

Thanks in advance

**Comment by bastula** [comment]
It matches the `z` coordinate of the dose plane with the `z` coordinate of the current structure. So if the structure is tilted, the calculation will be incorrect. By, `z` I mean sup-inf direction. Unfortunately, that means you will have to do some interpolation.

**Comment by sama2689** [comment]
The structure is not tilted, but translated in z so that some of the slices of the structure are now in between slices of the rt-dose. Would this be a different situation than tilt?

**Comment by bastula** [comment]
Yes, the dose grid in this case would be interpolated to the closest 'z' plane. Please see here for implementation: https://github.com/dicompyler/dicompyler-core/blob/de6a0ed7f3a928399f799bce0acb6018e595a8bf/dicompylercore/dicomparser.py#L738

**Comment by sama2689** [comment]
Oh perfect! Then if I understand correctly so long as the orientation stays (i.e. no tilt) the same the dvh calculation script is robust to translations in x,y and z.

**Comment by bastula** [comment]
Yes you are correct!
