### ISSUE TITLE
Dose plane not found for %s. Using %s to calculate contour volume.'

### ISSUE THREAD

**Issue by sama2689** [dicompyler/dicompyler-core#241]
I am trying to apply a translation shift to an rtss prior to extracting the dvh. I.e. translating a 3D contour by some vector [x,y,z] and then computing the dvh using the translated rtss and rtdose. to this end, I have slightly modified the [`get_dvh`](https://dicompyler-core.readthedocs.io/en/latest/_modules/dicompylercore/dvhcalc.html#get_dvh) function by adding some shift vector to all coordinate triplets in `s['planes']` and assigning keys corresponding to the new z values. 

I believe that this function is able to handle that, and it seems to work without issue. However, I am getting a warning that "Dose plane not found for %s. Using %s to calculate contour volume.' in the logger, which I don't quite understand. Will this affect accurate calculation of the DVH or any relevant features or can I safely ignore this warning?

My function to translate the dvh is provided in a previous issue: https://github.com/dicompyler/dicompyler-core/issues/240

Thanks in advance.

**Comment by bastula** [comment]
It just means it wasn't able to find that exact slice `z` position in the dose grid. It will use interpolation to extract the dose plane at that `z`. So thus it should be fairly accurate.
