### ISSUE TITLE
Is it possible to compute the DVH of joint structures?

### ISSUE THREAD

**Issue by sama2689** [dicompyler/dicompyler-core#245]
I don't have access to an RT-struct file, I just have the outputs. In it I have 2 structs for left and right parotid glands, but I would like a single struct which is a combination of the two. Is it possible to compute the DVH to these two structs as a merged entity? e.g. a single DVH for both parotid glands instead of 2 DVHs for each.

Thanks

**Comment by bastula** [comment]
I think you would have to merge the structure contours and assemble them before submitting it for DVH calculation. You could do that via the `shapely` python library.

**Comment by sama2689** [comment]
Sure I can do that. This would involve creating a function for a contour boolean (union). If there is interest in this could submit this function as a PR once I finish it?

**Comment by bastula** [comment]
Possibly. I know @cutright has done some work in this area. Maybe he can chime in to see if this is something that can be easily added?

**Comment by cutright** [comment]
[DVH Analytics](http://dvhanalytics.com) almost has the functionality you want. You can use [dvha.tools.roi_formatter.dicompyler_roi_to_sets_of_points](https://github.com/cutright/DVH-Analytics/blob/a168cf67709b7a60d0d311a294801954421c1ad1/dvha/tools/roi_formatter.py#L276) with the output from dicompyler-core's ``GetStructureCoordinates``.  Then use [dvha.tools.roi_geometry.union](
https://github.com/cutright/DVH-Analytics/blob/a168cf67709b7a60d0d311a294801954421c1ad1/dvha/tools/roi_geometry.py#L32).  The only thing left is to write a function to invert ``dicompyler_roi_to_sets_of_points``.

Frankly, it's probably easier to write a new function that sticks to dicompyler-core's format, and maybe just use DVHA's union as inspiration.
