### ISSUE TITLE
D100 is 0Gy

### ISSUE THREAD

**Issue by marcmorcos** [dicompyler/dicompyler-core#25]
When calculating D100, it calculates as 0.00Gy.
Technically, 0Gy will always satify D100 for cummulative DVH but I believe the highest dose to satify D100 should be the one stated. I believe the code isn't doing that.

**Comment by bastula** [comment]
I can see what you are saying. This is mostly relevant for target structures.

Let's try to reproduce with the test data to see if this works correctly.

**Comment by bastula** [comment]
Resolved in #74.
