### ISSUE TITLE
Structure volume calculation dependent on RTDose

### ISSUE THREAD

**Issue by marcmorcos** [dicompyler/dicompyler-core#26]
This would be an issue for planning systems which export a limited dose grid (i.e. Oncentra Masterplan, brachytherapy). Structure volume should be calculated straight from RTSS dicom. It seems to be calculating volume by counting voxels of structure which overlap within dose grid.

This is probably an issue when using dvhcalc only. This may be an issue when trying to convert to relative volume.

**Comment by bastula** [comment]
See this commit: https://github.com/dicompyler/dicompyler-core/commit/00839519aa6c7b4f5917bc0daa4145bd2b0c5eb6 for a new function that can calculate volume for a structure. This functionality depends on the Shapely library.

You can manually set the volume on your calculated DVH after creating it using the function: `absolute_volume`.

**Comment by graftedlife** [comment]
Sorry I'm a bit confused and need your help--

1. We ran the 'Basic Usage' codes in README.rst (on the main page of dicompyler-core) using files in dicompyler-core-master/tests/testdata/example_data. But it seems that 

`rtdose = dicomparser.DicomParser("rtdose.dcm")
heartdvh = dvh.DVH.from_dicom_dvh(rtdose.ds, 5)`

and

`dvhcalc.get_dvh("rtss.dcm", "rtdose.dcm", 5)`

do not yield the same results of volume calculation. And the volume displayed on the GUI seems to be based on the former:

![7861557985211](https://user-images.githubusercontent.com/12371526/39352090-32650436-4a36-11e8-9245-bde61ba8341f.jpg)

2. There seems to be different volume calculation methods (using rtss) in dicompyler: CalculateVolume in dvhdata.py (https://github.com/bastula/dicompyler/blob/master/dicompyler/dvhdata.py) and CalculateStructureVolume in dicomparser.py (https://github.com/dicompyler/dicompyler-core/blob/master/dicompylercore/dicomparser.py). These two also do not yield the same results of volume calculation.

Could you please help clarify which one I should use?

Many thanks!

**Comment by bastula** [comment]
Hi there,

Answers to your questions using same numbered list:
1. The former uses the inherent DVH data embedded in the RT dose plan (exported from Eclipse). The latter is independently calculated and will show some minor differences.
2. `CalculateStructureVolume` was added to `dicomparser.py` to independently calculate volume from RTSS in case an RTSS/RTDOSE combination is not present. `dvhdata.py` was used in dicompyler but will be swapped to use `CalculateStructureVolume` in the future as it is more accurate.

I would recommend using CalculateStructureVolume in `dicomparser.py` unless you are unable to resolve the Shapely requirement.

**Comment by bastula** [comment]
Closing due to resolution in https://github.com/dicompyler/dicompyler-core/commit/00839519aa6c7b4f5917bc0daa4145bd2b0c5eb6.
