### ISSUE TITLE
Decubitus orientation

### ISSUE THREAD

**Issue by darcymason** [dicompyler/dicompyler-core#274]
I'm hoping for some guidance on DVHs in decubitus situation - I have CT and RTDOSE files with ImageOrientationPatient of [0, -1, 0, 1, 0, 0] and I get empty DVHs returned.

On calling `get_dvh` with debugging on, I see many lines like:
`Dose plane not found for -100.00. Using -140.25 to calculate contour volume`.

I see that there have been some issues and PR related to non-HFS orientation (e.g. #183), and in reviewing the code, I don't see any particular limitations for decubitus.  I'm using the latest commit from master.

I haven't pursued it in further detail hoping to get some pointers in the right direction for further investigation.  For example I haven't tried changing any of the optional parameters to `get_dvh`.

Thanks

**Comment by bastula** [comment]
Hi Darcy,

Thanks for looking into this. I haven't explicitly tried decubitus orientation for DVH calculation, but in theory it should work. There may be an issue with IPP and IOP coordinates in the calculation that doesn't account for the 90 degree rotation. Maybe it's worth checking see if the RT Structure Set is properly drawn on the CT? If that doesn't display properly, I would assume the dose grid would also have incorrect coordinates when doing the patient-to-pixel mapping.

**Comment by darcymason** [comment]
Thanks, Adit, I'll take another look at the calc using ipp and iop to try to determine if it is completely general.  Do you have a reference for where that came from?

I'm a little surprised by the problems, because I would have thought that a feet-first patient being oriented differently would not really affect anything as long as the dose and the CT agree on it.  I even tried changing both to standard HFS orientation but the same error occurs.

As for the RT Structure Set, my understanding of DICOM is that contours reference the CT slices they belong to, so that should guarantee alignment in the plane. Perhaps there is something non-standard in the set I am working with - I can check with my source and see if there is anything else unusual about these plans/doses/structure sets.

**Comment by darcymason** [comment]
I did some further investigation into this decubitus issue and think I understand what is going on.

There are two problems:
- the [plane calculation in `DicomParser.GetDoseGrid()`](https://github.com/dicompyler/dicompyler-core/blob/5c2622ce6c1b32a467f8143ceaf94a70e9c1fe36/dicompylercore/dicomparser.py#L782) is essentially assuming a 'standard' non-decubitus orientation. The ipp[0] and ipp[4] in decubitus are 0, so `planes` becomes an array of a constant ipp[2]

- the [LUT returned by `DicomParser.GetPatientToPixelLUT()`](https://github.com/dicompyler/dicompyler-core/blob/5c2622ce6c1b32a467f8143ceaf94a70e9c1fe36/dicompylercore/dicomparser.py#L494) assumes a 'standard' orientation.  Again because of orientation[0] being 0 in decubitus, the two loops over i and j are not in the axis through which the x and y are changing, and instead each return an array with constant values.

I see some different options for how to deal with this:

- special-case the decubitus, and before any calculations, rotate (`numpy.rot90`) the dose array clockwise or counterclockwise  and alter the iop back to non-decubitus to sort of trick the algorithm into doing the right thing. I believe numpy does this through a view, so it is not actually shifting the array in memory and would be quick
- keep track of which axes correspond to x and y directions, and use them according in code throughout
- perhaps it is only a matter of shifting the axes in `dosegrid` [here](https://github.com/dicompyler/dicompyler-core/blob/5c2622ce6c1b32a467f8143ceaf94a70e9c1fe36/dicompylercore/dvhcalc.py#L183) although I'm not sure.


In any case, I recommend the code be updated to throw `NotImplementedError` for cases it doesn't handle,
which at the moment is probably any other than the four combinations of head-first/feet-first and supine/prone.

I have a toy structure set and dose (10x10 grid) that I could use for putting some tests together.  I'm happy to do a PR but would appreciate thoughts on which approach above (or other solution) would be best.

Thanks

**Comment by darcymason** [comment]
I've come across another little problem while looking into this, that I'll document here just to remember (and will try to fix in a PR also):  `get_interpolated_dose` does not check `GetDoseGrid` for an empty array being returned, and so for interpolated doses or when `use_structure_extents` is on, and contours extend past the dose grid, an IndexError is raised because the [next line](https://github.com/dicompyler/dicompyler-core/blob/5c2622ce6c1b32a467f8143ceaf94a70e9c1fe36/dicompylercore/dvhcalc.py#L491) uses a 2d indexing.

**Comment by bastula** [comment]
Thanks for the thorough investigation. Much appreciated.

Regarding the most ideal situation:

> * special-case the decubitus, and before any calculations, rotate (`numpy.rot90`) the dose array clockwise or counterclockwise  and alter the iop back to non-decubitus to sort of trick the algorithm into doing the right thing. I believe numpy does this through a view, so it is not actually shifting the array in memory and would be quick

Sounds like this would be the fastest method if it really does utilize a numpy view.
> * keep track of which axes correspond to x and y directions, and use them according in code throughout

Although this may be the most verbose, it would probably be best for the long term as it would be better documented for any other edge cases that come up in the future.
> * perhaps it is only a matter of shifting the axes in `dosegrid` [here](https://github.com/dicompyler/dicompyler-core/blob/5c2622ce6c1b32a467f8143ceaf94a70e9c1fe36/dicompylercore/dvhcalc.py#L183) although I'm not sure.

This may work, but might be also worth the time to reconfigure `DicomParser.GetPatientToPixelLUT` based on IOP/IPP and appropriately turn the dose grid / track the axes?

As a result I am leaning towards option number 2 so we could more easily test all possible orientations, but I am open to any of the above ideas.

Also thanks for finding that IndexError in `get_interpolated_dose`. That would be a nice fix.

**Comment by darcymason** [comment]
I've discovered another issue when coming back to this again.  It involves my 'toy' test cases which I strengthened by making a non-square dose grid and unequal pixel spacing in x and y directions.

I believe the `di` and `dj` in [GetPatientToPixelLUT](https://github.com/dicompyler/dicompyler-core/blob/5c2622ce6c1b32a467f8143ceaf94a70e9c1fe36/dicompylercore/dicomparser.py#L481) are reversed.  In DICOM, the [PixelSpacing first value is delta-row](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_10.7.html#sect_10.7.1.3) but in the matrix it is used in the x direction, which is across columns.

I confirmed with a clean clone of the dicompyler-core repo that reversing di and dj still passes all tests.  

[In my fork's tests](https://github.com/darcymason/dicompyler-core/pull/1) (still a bit messy with new code causing failure of an old test), my unequal pixel-spacing tests pass as expected with them reversed.

I suspect this hasn't been a problem because unequal pixel spacing in rtdose datasets is probably almost never done in the real world.

If you don't mind having a look and confirming, I'd appreciate it.  I could make a separate PR if you like to get this one changed independent of the decubitus question.

**Comment by gacou54** [comment]
Hi, I was going to raise an issue pointing to the fact that the PixelSpacing (`di` and `dj`) seems reversed before seeing this issue. After a quick investigation I came to the same conclusion as @darcymason. 

FYI, a similar reversal seems to have been observed here: https://github.com/pymedphys/pymedphys/pull/1571. It might help for the investigation. Best of luck!

**Comment by bastula** [comment]
Hi @darcymason and @gacou54, thanks for bringing up the `di` and `dj` issues with `PixelSpacing`. I think it was also mentioned in past issues and should be corrected.

@darcymason I will try to take a look at your fork in the next day or so. I think if it's a simple fix, maybe we do it as a separate PR. Also briefly looking at https://github.com/pymedphys/pymedphys/pull/1571 as @gacou54 mentioned, it may be worth to put a comment to indicate `di` and `dj` as row and column spacing correctly, once it has been reversed.

**Comment by bastula** [comment]
@darcymason Looking through your code, it may be ok to do 1 PR as the issues are related. I see that you already made the nomeclature changes to `di` and `dj` so that would be fine.

**Comment by darcymason** [comment]
> I see that you already made the nomeclature changes to `di` and `dj` so that would be fine.

I was just writing to mention that when I saw your next comment... basically I have been trying to change nomenclature, comments, etc. everywhere that references to x or y, to col and row when that is what is really used, leaving x and y only for references to real-world coordinates.  

This after flirting with matrix rotation as the solution, but running into some problems there, so going back to tracking which index is x vs y and going forward from there.  I think I'm getting close...
