### ISSUE TITLE
Support Non-HFS orientations for RT Dose

### ISSUE THREAD

**Issue by bastula** [dicompyler/dicompyler-core#29]
GetDoseGrid does not work correctly for combination of Feet First Supine and Prone patient position.

See https://github.com/bastula/dicompyler/issues/107#issuecomment-341188102 for more details.

Ideally all patient orientations should be listed and supported.

**Comment by bastula** [comment]
Need to check support for `GetDoseGrid` for non-HFS orientations. Look at https://gitlab.com/pymedphys/pymedphys/-/merge_requests/49/diffs for some inspiration. Would also need some unit tests for all other orientations.

**Comment by gramsm** [comment]
Looking forward to the fix.  I can provide some test cases if you need them.  Thanks.
