### ISSUE TITLE
How to get the value of 'D0.5cc'？

### ISSUE THREAD

**Issue by genhao3** [dicompyler/dicompyler-core#294]
After executing this statement 'calcdvh = dvhcalc.get_dvh(rtstructFile, rtdoseFile, key)'，how to get the value of 'D0.5cc'？

**Comment by sama2689** [comment]
If the dvh is calculated correctly this can be done with calcdvh.statistic('D0.5cc')' I think?

**Comment by genhao3** [comment]
> If the dvh is calculated correctly this can be done with calcdvh.statistic('D0.5cc')' I think?

I found the value of calcdvh.statistic('D0.5cc') is equal to the value of calcdvh.statistic('D5cc')

**Comment by sama2689** [comment]
Could you share a plot of the DVH? Is it possible that the DVH flattens before 5cc?
