### ISSUE TITLE
Syntax question on getting isodose points

### ISSUE THREAD

**Issue by sama2689** [dicompyler/dicompyler-core#311]
I'm not quite clear on how the GetIsodosePoints function translates into an actual isodose as we understand it as a function of prescription dose. I see that the default scalings is 0.5 relative to the DoseGridScaling, but what does this mean? If I set this to 0.5 then are we getting the 50% isodose as defined as 50% of the maximum? Or is this 50% of the DoseGridScaling in Gy? I'm a bit confused about how, for example, we would get say the isodose for 95% of the prescription dose.

**Comment by sama2689** [comment]
I think there is an errorr in the documentation here: 
![image](https://user-images.githubusercontent.com/27438633/192512460-48f32047-2ca9-406c-8e81-2a3fe11d0d28.png)
 I think the description of the function is confusing the level and the threshold and using them interchangably?

**Comment by bastula** [comment]
Yes you are correct, the docstring is incorrect and should be flipped. Thank you for catching this! Regarding your original question, the isodose level is relative to the `DoseGridScaling` attribute. In most cases, this may be prescription dose, but it is some normalization that the treatment planning system will use.
