### ISSUE TITLE
Get DVH for a fractional volume (i.e. D0.1cc) using DVHcalc

### ISSUE THREAD

**Issue by marcmorcos** [dicompyler/dicompyler-core#347]
If calculating DVH using dicom RT data, we can look at the D2cc using:
```
calcdvh = dvhcalc.get_dvh("rtss.dcm", "rtdose.dcm", 5)
calcdvh.D2cc

```

What can be done if we want something like D0.1cc?
Thanks

**Comment by bastula** [comment]
You can get that via `calcdvh.statistic("D0.1cc")`. Any arbitrary statistic can be obtained via the `statistics` accessor: https://dicompyler-core.readthedocs.io/en/latest/dicompylercore.html#dicompylercore.dvh.DVH.statistic
