### ISSUE TITLE
Using a PosixPath for a file raises an AttributeError

### ISSUE THREAD

**Issue by TBurlacu-tud** [dicompyler/dicompyler-core#365]
The problem is essentially in the title. When I specify the path to the dicom file using `Path('/foo/bar/file.dcm')` I get an AttributeError whereas when I specify the path as `'/foo/bar/file.dcm'` it works fine.

**Comment by bastula** [comment]
This will be addressed by the changes in #367.

**Comment by bastula** [comment]
Fixed by #367.
