### ISSUE TITLE
D100, D98, D2cc calculation on differential dvh

### ISSUE THREAD

**Issue by inamoto85** [dicompyler/dicompyler-core#58]
Hi Bastula,

Thank you for this wonderful package first!
I noticed that when calculating D100, D98, etc with differential DVH, the function does not return correct value from `dvh.statistic`. 
Maybe a wraparound to calculate the statistics from `DVH.cumulative` could be added in the function?

**Comment by bastula** [comment]
Thanks for reporting this. Yes I agree that there is a discrepancy when reporting statistics on the differential DVH. As you mentioned, the statistics from `DVH.cumulative` can be used to calculate the statistics for a differential DVH.
