### ISSUE TITLE
Install via setup.py

### ISSUE THREAD

**Issue by robmarkcole** [dicompyler/dicompyler-core#7]
Hi Adit
I previously installed dicompyler-core using pip and it worked OK.
I have now forked dicompyler-core and attempted to install my version using setup.py, but it fails and I receive the message below. Is there a fault in setup.py or my usage of it? Is it possible to install my fork 'over' the version I have already? Please note I am on a hospital computer without admin rights, I am not sure if this could be part of the problem, but I assume not since previous install via pip was successful.
Cheers
Robin

`C:\Users\......\Desktop\GitHub\Useful-python-for-medical-physics\My
 Forks\dicompyler-core>python setup.py install

running install
running bdist_egg
running egg_info
writing dependency_links to dicompyler_core.egg-info\dependency_links.txt
writing top-level names to dicompyler_core.egg-info\top_level.txt
writing requirements to dicompyler_core.egg-info\requires.txt
writing dicompyler_core.egg-info\PKG-INFO
reading manifest file 'dicompyler_core.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory'*'
warning: no previously-included files matching '*.DS_Store' found under directory '*'
writing manifest file 'dicompyler_core.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
copying dicompylercore\dvh.py -> build\lib\dicompylercore
creating build\bdist.win32\egg
creating build\bdist.win32\egg\dicompylercore
copying build\lib\dicompylercore\config.py -> build\bdist.win32\egg\dicompylercore
copying build\lib\dicompylercore\dicomparser.py -> build\bdist.win32\egg\dicompylercore
copying build\lib\dicompylercore\dvh.py -> build\bdist.win32\egg\dicompylercore
copying build\lib\dicompylercore\dvhcalc.py -> build\bdist.win32\egg\dicompylercore
copying build\lib\dicompylercore\util.py -> build\bdist.win32\egg\dicompylercore

copying build\lib\dicompylercore\__init__.py -> build\bdist.win32\egg\dicompylercore
byte-compiling build\bdist.win32\egg\dicompylercore\config.py to config.cpython-35.pyc
byte-compiling build\bdist.win32\egg\dicompylercore\dicomparser.py to dicomparser.cpython-35.pyc
byte-compiling build\bdist.win32\egg\dicompylercore\dvh.py to dvh.cpython-35.pyc

Sorry: TabError: inconsistent use of tabs and spaces in indentation (dvh.py, line 290)
byte-compiling build\bdist.win32\egg\dicompylercore\dvhcalc.py to dvhcalc.cpython-35.pyc
byte-compiling build\bdist.win32\egg\dicompylercore\util.py to util.cpython-35.pyc
byte-compiling build\bdist.win32\egg\dicompylercore\__init__.py to __init__.cpython-35.pyc
creating build\bdist.win32\egg\EGG-INFO
copying dicompyler_core.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying dicompyler_core.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying dicompyler_core.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying dicompyler_core.egg-info\not-zip-safe -> build\bdist.win32\egg\EGG-INFO
copying dicompyler_core.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying dicompyler_core.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO

creating 'dist\dicompyler_core-0.5.2-py3.5.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing dicompyler_core-0.5.2-py3.5.egg
creating c:\users\rcole02.royalsurrey\appdata\local\continuum\anaconda3\lib\site
-packages\dicompyler_core-0.5.2-py3.5.egg

error: could not create 'c:\users\.....\appdata\local\continuum\an
aconda3\lib\site-packages\dicompyler_core-0.5.2-py3.5.egg': Access is denied

**Comment by bastula** [comment]
Make sure you `pip uninstall dicompyler-core` before installing your fork.

You may also want to consider using `python setup.py develop` to get an in-place installation for development purposes.

**Comment by robmarkcole** [comment]
python setup.py develop has worked. I have edited the dvh class (print('Robin')) and saved the changes, but this does not seem to take effect when I run the import statement again and re-init my dvh object. Is there another step to make changes effective?
Cheers
Robin

![image](https://cloud.githubusercontent.com/assets/11855322/19308338/df6d910a-9076-11e6-9049-c8ff8f21a83f.png)

**Comment by bastula** [comment]
You can add the following lines to your notebook to enable autoreload functionality:

```
%load_ext autoreload
%autoreload 2
```

I find it quite useful when testing modules. You may have to still re-execute cells above if you instantiated an object in a previous cell.
