### ISSUE TITLE
RTSTRUCT dicom files from Oncentra Prostate software produce empty DVH

### ISSUE THREAD

**Issue by gacou54** [dicompyler/dicompyler-core#80]
Hi, first of all thank you for this nice library!

I encounter a problem when calculating DVH with RTSTRUCT dicom files from Oncentra Prostate v4 software. The resulting DVH is always empty. This is because the dataset in those RTSTRUCT files does not have a `ContourImageSequence` tag. There is the condition in `GetStructureCoordinates` method where it appears (in `dicomparser.py`):  

![contourimagesequence](https://user-images.githubusercontent.com/25424166/50058163-66762980-0142-11e9-955e-0daf3339d5b3.png)

This tag does not seems to be used later in the code.

As you can see, this tag is not in RTSTRUCT dicom files from Oncentra Prostate v4:
![contourimagenotthere](https://user-images.githubusercontent.com/25424166/50058241-72162000-0143-11e9-9ee9-f75422f112d7.png)

But in other cases (not  Oncentra Prostate) they are:
![contourimageisthere](https://user-images.githubusercontent.com/25424166/50058252-a2f65500-0143-11e9-96da-d83c7ceabccc.png)

I have solved my problem by simply removing this condition:
https://github.com/dicompyler/dicompyler-core/compare/master...gacou5:bug/OCP-dicom-file-fail

I was wondering if there was any reason for the presence of this condition that I have not find out. If no I could do a Pull Request to remove this.

Thank you,
Gabriel

**Comment by bastula** [comment]
Hi no problem and thank you for the kind words.

I believe you are correct. This condition is definitely not used anywhere and can be safely removed.

Also according to the DICOM standard it is a Type 3 element and thus isn't guaranteed to be present.

If you want to make a PR about this, I would be glad to merge it.

Thanks!
