### ISSUE TITLE
D100 still returns value of 0

### ISSUE THREAD

**Issue by mbolt01** [dicompyler/dicompyler-core#85]
Hi,

I see this has tried to be fixed in #74 but I am still getting a returned value of 0Gy.

D99.99 gives a value of 4.9Gy.
D99.999 gives 0Gy.
D100 gives 0Gy.

This is a brachy plan created in and exported from the Oncentra brachy TPS so now sure if that would make any difference?
For our brachy plans this is an important statistic to be able to extract, so wondered if there might be a workaround in the meantime?

I am using dicompyler-core version 0.5.4.

Thanks,

Matt

**Comment by mbolt01** [comment]
Sorry, I think this issue may be null and void. I think v 0.5.4 doens't contain the fix. I'll try and get the master code form github and re-test.

**Comment by gacou54** [comment]
Hello,

I think it's because the version in Pypi is not up to date (it's the 0.5.4 version as you said).
Installing the 0.5.5 directly from github should fix the problem.

`$ pip uninstall dicompyler-core`
and 
`$ pip install git+https://github.com/dicompyler/dicompyler-core.git`

For the numpy version I think you are right. It would be better to support older version.

Gabriel

**Comment by mbolt01** [comment]
Hi,

Thanks for confirming this. 
I don't have Git on my work PC. IS it possible to do a similar install from Github directly without this? For now I have just created a new version of the dvh.py file to use and this is working OK.

**Comment by gacou54** [comment]
You can download the zip file on the `clone or download` button on the main dicompyler-core's github page.
Extract the zip file and open a prompt command in the path where dicompyler-core-master directory is.
Finally to install dicompyler-core run the command:

`$ pip install -e dicompyler-core-master`

Do you need the compatibility for numpy versions under 1.12 soon? I could do a Pull Request to solve this issue.

Gabriel

**Comment by mbolt01** [comment]
I'm sure it would be useful to make it compatible with the earlier versions for the sake of this very small change.

**Comment by bastula** [comment]
dicompyler 0.5.5 has been released and can be downloaded so this issue can be closed.
