### ISSUE TITLE
Memory efficient use

### ISSUE THREAD

**Issue by robmarkcole** [dicompyler/dicompyler-core#9]
I wish to load up to 30 plans for simultaneous analysis, since each plan is approx. 46 Mb this may be a problem for my PC (30*46 = 1.4 Gb). Is there a more memory efficient way to work with a large number of plans?
Cheers
##

**Comment by bastula** [comment]
One way to avoid this is to load the array via [`numpy.memmap`].(https://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html)

Also consider looking at the discussion in pydicom: darcymason/pydicom#137

**Comment by bastula** [comment]
Looks like this was resolved in: https://github.com/dicompyler/dicompyler-core/commit/1bff07bfd112293ec769d8aa76dca6bfef1f3a92
