### ISSUE TITLE
Dicomparser can't parse dicom files

### ISSUE THREAD

**Issue by thompa2** [dicompyler/dicompyler-core#90]
Running into an odd issue. Did a fresh install of dicompyler-core today and tried to load in a few dicom files, except the dicomparser can't read them.  

`dp = dicomparser.DicomParser(datafolder+structloc+structfile)`

produces this:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-89ea0280c591> in <module>
----> 1 dp = dicomparser.DicomParser(datafolder+structloc+structfile)

~/anaconda3/envs/sandbox/lib/python3.6/site-packages/dicompylercore/dicomparser.py in __init__(self, dataset)
     42             try:
     43                 self.ds = \
---> 44                     read_file(dataset, defer_size='100', force=True)
     45             except:
     46                 # Raise the error for the calling method to handle

~/anaconda3/envs/sandbox/lib/python3.6/site-packages/pydicom/filereader.py in dcmread(fp, defer_size, stop_before_pixels, force, specific_tags)
    878     try:
    879         dataset = read_partial(fp, stop_when, defer_size=defer_size,
--> 880                                force=force, specific_tags=specific_tags)
    881     finally:
    882         if not caller_owns_file:

~/anaconda3/envs/sandbox/lib/python3.6/site-packages/pydicom/filereader.py in read_partial(fileobj, stop_when, defer_size, force, specific_tags)
    769         dataset_class = FileDataset
    770     new_dataset = dataset_class(fileobj, dataset, preamble, file_meta_dataset,
--> 771                                 is_implicit_VR, is_little_endian)
    772     # save the originally read transfer syntax properties in the dataset
    773     new_dataset.set_original_encoding(is_implicit_VR, is_little_endian,

~/anaconda3/envs/sandbox/lib/python3.6/site-packages/pydicom/dataset.py in __init__(self, filename_or_obj, dataset, preamble, file_meta, is_implicit_VR, is_little_endian)
   1362             big-endian.
   1363         """
-> 1364         Dataset.__init__(self, dataset)
   1365         self.preamble = preamble
   1366         self.file_meta = file_meta

~/anaconda3/envs/sandbox/lib/python3.6/site-packages/pydicom/dataset.py in __init__(self, *args, **kwargs)
    175         """Create a new Dataset instance."""
    176         self._parent_encoding = kwargs.get('parent_encoding', default_encoding)
--> 177         dict.__init__(self, *args)
    178         self.is_decompressed = False
    179 

~/anaconda3/envs/sandbox/lib/python3.6/site-packages/pydicom/dataset.py in __getitem__(self, key)
    595                 from pydicom.filereader import read_deferred_data_element
    596                 data_elem = read_deferred_data_element(
--> 597                     self.fileobj_type, self.filename, self.timestamp,
    598                     data_elem)
    599 

~/anaconda3/envs/sandbox/lib/python3.6/site-packages/pydicom/dataset.py in __getattr__(self, name)
    518         if tag is None:  # `name` isn't a DICOM element keyword
    519             # Try the base class attribute getter (fix for issue 332)
--> 520             return super(Dataset, self).__getattribute__(name)
    521         tag = Tag(tag)
    522         if tag not in self:  # DICOM DataElement not in the Dataset

AttributeError: 'Dataset' object has no attribute 'fileobj_type'

**Comment by bastula** [comment]
Seems to be a pydicom issue? `DicomParser` will raise any underlying pydicom issues as part of the file reading process. Maybe you can submit an anonymized file to their issue tracker?

**Comment by CHRIS-LIN-Jude** [comment]
while i delete the defer_size,it's useful
before 
```
class DicomParser:
    """Parses DICOM / DICOM RT files."""

    def __init__(self, dataset):

        if isinstance(dataset, Dataset):
            self.ds = dataset
        elif isinstance(dataset, (string_types, BytesIO)):
            try:
                self.ds = read_file(dataset, defer_size=100, force=True)
            except:
                # Raise the error for the calling method to handle
                raise
            else:
                # Sometimes DICOM files may not have headers,
                # but they should always have a SOPClassUID
                # to declare what type of file it is.
                # If the file doesn't have a SOPClassUID,
                # then it probably isn't DICOM.
                if not "SOPClassUID" in self.ds:
                    raise AttributeError
        else:
            raise AttributeError
```
After
```
class DicomParser:
    """Parses DICOM / DICOM RT files."""

    def __init__(self, dataset):

        if isinstance(dataset, Dataset):
            self.ds = dataset
        elif isinstance(dataset, (string_types, BytesIO)):
            try:
                self.ds = read_file(dataset, force=True)
            except:
                # Raise the error for the calling method to handle
                raise
            else:
                # Sometimes DICOM files may not have headers,
                # but they should always have a SOPClassUID
                # to declare what type of file it is.
                # If the file doesn't have a SOPClassUID,
                # then it probably isn't DICOM.
                if not "SOPClassUID" in self.ds:
                    raise AttributeError
        else:
            raise AttributeError
```

**Comment by bastula** [comment]
@CHRIS-LIN-Jude we can definitely remove `defer_size=100`. However I had put it in to speed up parsing hundreds/thousands of files. Another way to bypass this is to read in the dataset via `pydicom` and pass the resulting dataset as an object to the `DicomParser` constructor.

**Comment by CHRIS-LIN-Jude** [comment]
@bastula  After my test if I modify the `defer_size `**the input from int to string**, the function is still work and the IO speed is  2-3ms  faster than not using  `defer_size `  while read  one dicom file.
So I track this problem, and found there are some problem in pydicom/dataset.py the function `Dataset `
before
`defer_size=100`
After
`defer_size=str('512 kB')`

**Comment by bastula** [comment]
Do you want to try asking this to the `pydicom` forum or project page? I am more than happy to modify the code here, but it seems like it is a `pydicom` issue now.
