### ISSUE TITLE
Shouldn't the range be calculated using max-min rather than max+min?

### ISSUE THREAD

**Issue by jam3sward** [dicompyler/dicompyler-core#99]
First of all, great work on Dicomplyer - it's a really nice piece of software!

I just noticed in this line of code that the window is calculated by adding the max+min values, whereas it looks like it should be max-min?
https://github.com/dicompyler/dicompyler-core/blob/54bb053db6b4e2a27eff216b7a1677f4d6eba2a0/dicompylercore/dicomparser.py#L413

The existing code window=abs(max)-abs(min) will work in most cases because, for example (min=0,max=700) will give window=700 and (min=-1000,max=6000) will give window=7000. However, (min=100,max=700) would give window=800 instead of window 600 as expected. However, using window=max-min looks like it would work in all cases.

**Comment by bastula** [comment]
I think you're right based on your examples. Thanks for catching this.
